### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by mikesdnielsen** [johnsensible/django-publish#5]
I'm using django-publish on a site, where I use permissions. 
However, I can't seem to find the permission for Can Publish and assign it. 
I'm not sure if this is an error or incorrect installation.

**Comment by johnsensible** [comment]
There should be a separate "Can publish" permission per model.  It _should_ be created automatically when you run syncdb.

What happens if you try this on a fresh install?

**Comment by mikesdnielsen** [comment]
I think it may be a result of using South. It appears that I have used South (unknowingly) on the django-publish app as well. 

I managed to re-add it using inspiration from this example: https://djangosnippets.org/snippets/698/
